<a href="https://colab.research.google.com/github/franchesco117/curso/blob/master/copia_ejercicio.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NumPy Exercises for Data Analysis

In [ ]:
# 1. Import numpy as np and see the version

# your code here
import numpy as np

print(np.__version__)


1.22.4


In [ ]:
# 2. Create a 1D array of numbers from 0 to 9
# your code here
import numpy as np

arr = np.arange(10)
print(arr)


[0 1 2 3 4 5 6 7 8 9]


In [ ]:
# 3. Create a 3×3 numpy array of all True’s
# your code here
import numpy as np

arr = np.ones((3, 3), dtype=bool)
print(arr)



[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [ ]:
# 4. Extract all odd numbers from arr
# your code here
import numpy as np

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
odd_numbers = arr[arr % 2 != 0]
print(odd_numbers)


[1 3 5 7 9]


In [ ]:
# 5. Replace all odd numbers in arr with -1
# your code here
import numpy as np

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr % 2 != 0] = -1
print(arr)


[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [ ]:
#  6. Convert a 1D array to a 2D array with 2 rows
# your code here
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
arr_2d = arr.reshape(2, -1)
print(arr_2d)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [ ]:
#  7. Stack arrays a and b vertically
# your code here
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

stacked = np.vstack((a, b))
print(stacked)


[[1 2 3]
 [4 5 6]]


In [ ]:
#  8. Stack the arrays a and b horizontally.
# your code here
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

stacked = np.hstack((a, b))
print(stacked)


[1 2 3 4 5 6]


In [ ]:
#  9. Get all items between 5 and 10 from a.
# your code here
import numpy as np

a = np.arange(15)
items_between_5_and_10 = a[(a > 5) & (a < 10)]
print(items_between_5_and_10)

# pass

[6 7 8 9]


In [ ]:
#  10. How to make a python function that handles scalars to work on numpy arrays?
# Hint
# Desired Output:
# a = np.array([5, 7, 9, 8, 6, 4, 5])
# b = np.array([6, 3, 4, 8, 9, 7, 1])
# pair_max(a, b)
# #> array([ 6.,  7.,  9.,  8.,  9.,  7.,  5.])


# your code here
import numpy as np

def pair_max(x, y):
    """Obtiene el máximo entre dos elementos escalares o arrays de NumPy"""
    max_func = np.vectorize(maxx)
    return max_func(x, y)

def maxx(x, y):
    """Obtiene el máximo de dos elementos"""
    if x >= y:
        return x
    else:
        return y

# Ejemplo de uso:
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
result = pair_max(a, b)
print(result)



[6 7 9 8 9 7 5]


In [ ]:
#  11. Swap columns 1 and 2 in the array arr.
# Hint
# Desired Output:
# [[0 2 1]
#  [3 5 4]
#  [6 8 7]]


arr = np.arange(9).reshape(3,3)
print(arr)
# your code here
import numpy as np

arr = np.arange(9).reshape(3, 3)
print("Array original:")
print(arr)

# Intercambiar las columnas 1 y 2
arr[:, [1, 2]] = arr[:, [2, 1]]

print("Array modificado:")
print(arr)



[[0 1 2]
 [3 4 5]
 [6 7 8]]
Array original:
[[0 1 2]
 [3 4 5]
 [6 7 8]]
Array modificado:
[[0 2 1]
 [3 5 4]
 [6 8 7]]


In [ ]:
#  12. Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10.
# Hint
# The desired Output should be like the following one:
#  [[ 8.50061025  9.10531502  6.85867783]
#   [ 9.76262069  9.87717411  7.13466701]
#   [ 7.48966403  8.33409158  6.16808631]
#   [ 7.75010551  9.94535696  5.27373226]
#   [ 8.0850361   5.56165518  7.31244004]]

import numpy as np

random_array = np.random.uniform(5, 10, size=(5, 3))
print(random_array)


[[6.70606262 9.10241634 9.46341136]
 [5.43524317 5.62832463 9.37896397]
 [8.50805423 7.85186543 7.46874207]
 [8.63639376 9.24142827 7.54906393]
 [5.21347549 5.60355226 9.94837646]]
